### ISSUE TITLE
How to include the package pagemachine/authorized-keys into my project

### ISSUE THREAD

**Issue by falkulrich** [pagemachine/authorized-keys#5]
After installing the package with composer, I can't use the classes of the package. What has to be done, to be able to use the class 'AuthorizedKeys' in the way shown in the read me file?

I always get the error: Class 'AuthorizedKeys' not found

**Comment by mbrodala** [comment]
In your direct mail you wrote that you tried this and wrote that _it didn't work_:

```
require_once "vendor/autoload.php";

$path = '/.ssh/authorized_keys';
$authorizedKeys = AuthorizedKeys::fromFile($path);
```

What exactly was the problem here? Aside from the directory which should be `/absolute/path/to/.ssh/authorized_keys` or `getenv('HOME') . '/.ssh/authorized_keys` this is correct.

If you have any error messages or similar please let me know.

**Comment by falkulrich** [comment]
This is a local docker container so the $path is correct. The Problem was that the class 'AuthorizedKeys' was not resolved. I just found out, that the following line was missing:

`use Pagemachine\AuthorizedKeys\AuthorizedKeys;`

**Comment by mbrodala** [comment]
Uh, yeah. I'll add that to the README.
